### ISSUE TITLE
Tests do not compile with GHC 9.0.1

### ISSUE THREAD

**Issue by danwdart** [Soostone/retry#71]
Think it's to do with the `forall` fussiness, as it type errors upon:

`fmap (something) genDuration` in `test/Tests/Control/Retry.hs`.

Workaround Nix derivation override:

```nix
{
  retry = (self.callHackage "retry" "0.8.1.2" {}).overrideDerivation(self: {
    prePatch = ''
      sed -i 's/fmap \(.*\) genDuration/fmap (\\x -> \1 x) genDuration/g' test/Tests/Control/Retry.hs
    '';
  });
}
```

helps by eta-expanding as recommended.

**Comment by MichaelXavier** [comment]
I can't easily test this until GHC 9.x hits at least stackage nightly, so I think I'll sit on this until then.

**Comment by pjones** [comment]
FYI:

```
$ nix-build -A haskell.packages.ghc901.retry '<nixpkgs>'
...
Preprocessing test suite 'test' for retry-0.8.1.2..
Building test suite 'test' for retry-0.8.1.2..
[1 of 3] Compiling Control.Retry    ( src/Control/Retry.hs, dist/build/test/test-tmp/Control/Retry.o )
[2 of 3] Compiling Tests.Control.Retry ( test/Tests/Control/Retry.hs, dist/build/test/test-tmp/Tests/Control/Retry.o )

test/Tests/Control/Retry.hs:416:29: error:
    • Couldn't match type ‘RetryPolicyM mr’ with ‘RetryPolicy’
      Expected: Int -> RetryPolicyM mr
        Actual: Int -> RetryPolicy
    • In the first argument of ‘fmap’, namely ‘constantDelay’
      In the expression: fmap constantDelay genDuration
      In an equation for ‘genConstantDelay’:
          genConstantDelay = fmap constantDelay genDuration
    • Relevant bindings include
        genConstantDelay :: mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:416:5)
        genPolicyNoLimit :: Range Int -> mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:406:1)
    |
416 |     genConstantDelay = fmap constantDelay genDuration
    |                             ^^^^^^^^^^^^^

test/Tests/Control/Retry.hs:417:34: error:
    • Couldn't match type ‘RetryPolicyM mr’ with ‘RetryPolicy’
      Expected: Int -> RetryPolicyM mr
        Actual: Int -> RetryPolicy
    • In the first argument of ‘fmap’, namely ‘exponentialBackoff’
      In the expression: fmap exponentialBackoff genDuration
      In an equation for ‘genExponentialBackoff’:
          genExponentialBackoff = fmap exponentialBackoff genDuration
    • Relevant bindings include
        genExponentialBackoff :: mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:417:5)
        genConstantDelay :: mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:416:5)
        genPolicyNoLimit :: Range Int -> mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:406:1)
    |
417 |     genExponentialBackoff = fmap exponentialBackoff genDuration
    |                                  ^^^^^^^^^^^^^^^^^^

test/Tests/Control/Retry.hs:419:32: error:
    • Couldn't match type ‘RetryPolicyM mr’ with ‘RetryPolicy’
      Expected: Int -> RetryPolicyM mr
        Actual: Int -> RetryPolicy
    • In the first argument of ‘fmap’, namely ‘fibonacciBackoff’
      In the expression: fmap fibonacciBackoff genDuration
      In an equation for ‘genFibonacciBackoff’:
          genFibonacciBackoff = fmap fibonacciBackoff genDuration
    • Relevant bindings include
        genFibonacciBackoff :: mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:419:5)
        genFullJitterBackoff :: mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:418:5)
        genExponentialBackoff :: mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:417:5)
        genConstantDelay :: mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:416:5)
        genPolicyNoLimit :: Range Int -> mg (RetryPolicyM mr)
          (bound at test/Tests/Control/Retry.hs:406:1)
    |
419 |     genFibonacciBackoff = fmap fibonacciBackoff genDuration
    |                                ^^^^^^^^^^^^^^^^
builder for '/nix/store/vflfsgkxmz0fg83kcs871mkvv22dzh1i-retry-0.8.1.2.drv' failed with exit code 1
error: build of '/nix/store/vflfsgkxmz0fg83kcs871mkvv22dzh1i-retry-0.8.1.2.drv' failed
```

**Comment by prikhi** [comment]
Stackage nightly is on 9.0.1 now so you can do something like `stack test --resolver nightly` or `stack test --resolver ghc-9`

https://github.com/commercialhaskell/stackage/issues/6072

**Comment by prikhi** [comment]
Fix in `0.9.0.0` works for me, made a MR to bring this back in to stackage nightly.
